version: '3'
services:
  codegen:
    image: swaggerapi/swagger-codegen-cli:2.4.13
    volumes:
      - ../../target:/code-gen
      - ../../output:/swagger-output
      - ../../definition:/swagger-input
    entrypoint: java
    command: "-cp /code-gen/swagger-code-generator-node-typescript-1.0.0.jar:/opt/swagger-codegen-cli/swagger-codegen-cli.jar \
      io.swagger.codegen.SwaggerCodegen generate \
      -l node-typescript \
      --additional-properties=supportsES6=true
      -i swagger-input/swagger.yaml \
      -o /swagger-output"